export const enum RouterName {
  Login = "/login",
  Home = "/home",
  Info = "/info",
  Song = "/song",
  Singer = "/singer",
  SongList = "/songList",
  ListSong = "/listSong",
  Comment = "/Comment",
  Consumer = "/consumer",
  Collect = "/collect",
  Message = "/message",
  Feedback = "/feedback",
  Error = "/404",
  SignIn = "/",
  SignOut = "0",
}
